// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {models} from '../models';

export function AcceptPairing(arg1:string):Promise<void>;

export function ClearHistory():Promise<void>;

export function DeleteEntry(arg1:string):Promise<void>;

export function GeneratePairingCode():Promise<string>;

export function GetContext():Promise<context.Context>;

export function GetDeviceID():Promise<string>;

export function GetDevices():Promise<Array<models.Device>>;

export function GetHistory(arg1:number):Promise<Array<models.ClipboardEntry>>;

export function IsSyncActive():Promise<boolean>;

export function SearchHistory(arg1:string):Promise<Array<models.ClipboardEntry>>;

export function ShutdownTray():Promise<void>;

export function ToggleSync(arg1:boolean):Promise<void>;
