// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptPairing(arg1) {
  return window['go']['gui']['App']['AcceptPairing'](arg1);
}

export function ClearHistory() {
  return window['go']['gui']['App']['ClearHistory']();
}

export function DeleteEntry(arg1) {
  return window['go']['gui']['App']['DeleteEntry'](arg1);
}

export function GeneratePairingCode() {
  return window['go']['gui']['App']['GeneratePairingCode']();
}

export function GetContext() {
  return window['go']['gui']['App']['GetContext']();
}

export function GetDeviceID() {
  return window['go']['gui']['App']['GetDeviceID']();
}

export function GetDevices() {
  return window['go']['gui']['App']['GetDevices']();
}

export function GetHistory(arg1) {
  return window['go']['gui']['App']['GetHistory'](arg1);
}

export function IsSyncActive() {
  return window['go']['gui']['App']['IsSyncActive']();
}

export function SearchHistory(arg1) {
  return window['go']['gui']['App']['SearchHistory'](arg1);
}

export function ShutdownTray() {
  return window['go']['gui']['App']['ShutdownTray']();
}

export function ToggleSync(arg1) {
  return window['go']['gui']['App']['ToggleSync'](arg1);
}
